name: Captain's CI

on: [push]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: .cache/
        # An explicit key for restoring and saving the cache
        key: cl

    - uses: actions/checkout@v2
    - name: Use Node.js '16.x'
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test
      env:
        CI: true
